Fixes for How To Write How To Guides
ros-planning/moveit2_tutorials pull request #280
Opened 2022-01-14 19:00 UTC by cmelliott2

### Description

Minor language and formatting changes in How to Write a MoveIt How-To Guide

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-planning/moveit2/pulls) to support the maintainers

2022-01-14 19:12 UTC, jackcenter commented on doc/how_to_contribute/how_to_write_how_to_guides.rst
> +#. Write the specific learning objectives (i.e. what the reader will know when they finish reading this how-to).
```suggestion
#. Write the specific learning objectives (i.e., what the reader will know when they finish reading this how-to).
```

2022-01-14 19:12 UTC, jackcenter commented on doc/how_to_contribute/how_to_write_how_to_guides.rst
> +- :doc:`MoveIt Concepts: Tutorials </doc/concepts/tutorials>`
```suggestion
- :doc:`MoveIt Concepts: How-To Guide </doc/concepts/how_to_guide>`
```

2022-01-14 19:12 UTC, mlautman reviewed
Looks good to me but I don't have a linux machine build your changes locally. If someone else verifies that the syntax for links/formatting is correct, I approve

2022-01-14 19:21 UTC, corycrean requested changes

2022-01-14 19:21 UTC, corycrean commented on doc/how_to_contribute/how_to_write_how_to_guides.rst
>  #. Create a new file in the ``doc/how_to_guides`` directory with a ``.rst`` extension. The title should start with "How to" followed by the specific question being answered (e.g. "How to Write a Move
```suggestion
#. Create a new file in the ``doc/how_to_guides`` directory with a ``.rst`` extension. The title should start with "How to" followed by the specific question being answered (e.g., "How to Write a MoveIt How-To Guide").
```

2022-01-14 19:21 UTC, corycrean commented on doc/how_to_contribute/how_to_write_how_to_guides.rst
> +#. Write the specific learning objectives (i.e. what the reader will know when they finish reading this how-to).
```suggestion
#. Write the specific learning objectives (i.e., what the reader will know when they finish reading this how-to).
```

2022-01-14 19:21 UTC, corycrean commented on doc/how_to_contribute/how_to_write_how_to_guides.rst
> +  <Explanation of what the user should understand. Unlike a tutorial these are stand-alone and can assume the user has much more background.>
```suggestion
  <Explanation of what the user should understand. Unlike a tutorial, these stand alone and can assume the user has much more background.>
```

2022-01-14 19:29 UTC, cmelliott2 commented on doc/how_to_contribute/how_to_write_how_to_guides.rst
> +1. Fork the `MoveIt 2 Tutorials repository <https://github.com/ros-planning/moveit2_tutorials.git>`_ and start a new branch with an intuitive name (e.g., ``jack/how-to-tutorials``).
```suggestion
1. Fork the `MoveIt 2 Tutorials repository <https://github.com/ros-planning/moveit2_tutorials.git>`_ and start a new branch with an intuitive name (e.g., ``jack/how-to-write-how-tos``).
```

2022-01-14 19:34 UTC, cmelliott2 commented on doc/how_to_contribute/how_to_write_how_to_guides.rst
> +  <Explanation of what the user should understand. Unlike a tutorial these are stand-alone and can assume the user has much more background.>
```suggestion
  <Explanation of what the user should understand. Unlike a tutorial, these guides stand alone and can assume the user has much more background.>
```

2022-01-14 20:05 UTC, corycrean approved these changes

2022-01-15 00:10 UTC, tylerjw approved these changes

2022-01-15 00:11 UTC, merged