:sparkles: Visualizing in RViz Tutorial
ros-planning/moveit2_tutorials pull request #365
Opened 2022-05-17 22:06 UTC by tylerjw

This PR is based on:

- #262 

### Description

This new tutorial should introduce new users to MoveItVisualTools very quickly and provide some links for how they can learn more about its features and use cases.

2022-05-18 12:57 UTC, stephanie-eng commented on doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst
> +This tutorial will introduce you to a tool that can help you quickly understand what your MoveIt program is doing my rendering visualizations in RViz.
```suggestion
This tutorial will introduce you to a tool that can help you quickly understand what your MoveIt program is doing by rendering visualizations in RViz.
```

2022-05-18 13:10 UTC, stephanie-eng reviewed
I still need to follow along with the steps and try this, but fo rnow I've left some comments on spelling/grammar

2022-05-18 13:10 UTC, stephanie-eng commented on doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst
> +After each one of these changes you should rebuild your workspace to make sure you don't have any syntax errors.
```suggestion
After each one of these changes, you should rebuild your workspace to make sure you don't have any syntax errors.
```

2022-05-18 13:10 UTC, stephanie-eng commented on doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst
> +Next we will construct and initialize MoveItVisualTools after the construction of MoveGroupInterface.
```suggestion
Next, we will construct and initialize MoveItVisualTools after the construction of MoveGroupInterface.
```

2022-05-18 13:10 UTC, stephanie-eng commented on doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst
> +In the constructor we pass in the ROS node, the base link of the robot, the marker topic to use (more on this later), and the robot model (which we get from the move_group_interface).
This sentence reads a bit awkwardly. I think it's missing a comma, but even so, it sounds a bit Yoda-like. Not sure that my suggestion below is the best wording, but I'd re-word it one way or another.

```suggestion
We pass the following into the constructor: the ROS node, the base link of the robot, the marker topic to use (more on this later), and the robot model (which we get from the move_group_interface).
```

2022-05-18 13:10 UTC, stephanie-eng commented on doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst
> +Next we make a call to delete all the markers, this clears any rendered state out of RViz that we have left over from previous runs.
```suggestion
Next, we make a call to delete all the markers. This clears any rendered state out of RViz that we have left over from previous runs.
```

2022-05-18 13:10 UTC, stephanie-eng commented on doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst
> +Lastly we load remote control.
```suggestion
Lastly, we load remote control.
```

2022-05-18 13:10 UTC, stephanie-eng commented on doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst
> +After we've constructed and initialized we'd like to create some closures (function objects that have access to variables in our current scope) that we can use later in our program to render visualiz
```suggestion
After we've constructed and initialized, we now create some closures (function objects that have access to variables in our current scope) that we can use later in our program to help render visualizations in RViz.
```

2022-05-18 13:10 UTC, stephanie-eng commented on doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst
> +You might be asking yourself why we would create lambdas like this and the reason is simply to make the code that comes later easier to read and understand.
```suggestion
You might be asking yourself why we would create lambdas like this, and the reason is simply to make the code that comes later easier to read and understand.
```

2022-05-18 13:10 UTC, stephanie-eng commented on doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst
> +    prompt("Press 'next' in the RvizVisualToolsGui window to plan");
```suggestion
    prompt("Press 'Next' in the RvizVisualToolsGui window to plan");
```

2022-05-18 13:10 UTC, stephanie-eng commented on doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst
> +      prompt("Press 'next' in the RvizVisualToolsGui window to execute");
```suggestion
      prompt("Press 'Next' in the RvizVisualToolsGui window to execute");
```

2022-05-18 13:10 UTC, stephanie-eng commented on doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst
> +  [INFO] [1652822889.492940200] [hello_moveit.remote_control]: Waiting to continue: Press 'next' in the RvizVisualToolsGui window to plan
```suggestion
  [INFO] [1652822889.492940200] [hello_moveit.remote_control]: Waiting to continue: Press 'Next' in the RvizVisualToolsGui window to plan
```

2022-05-20 15:04 UTC, abake48 requested changes
Working on running through the tutorial right now but I have a few nitpicky grammatical suggestions from my read through.

2022-05-20 15:04 UTC, abake48 commented on doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst
> +Here I've augmented the code in the middle of your program with some new code.
```suggestion
Now we'll augment the code in the middle of your program.
```

2022-05-20 15:04 UTC, abake48 commented on doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst
> +Finally we need to add a ``Marker Array`` to render the visualizations we've added.
```suggestion
Finally, we need to add a ``Marker Array`` to render the visualizations we've added.
```

2022-05-20 15:04 UTC, abake48 commented on doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst
> +In a new terminal go to the workspace, source the workspace, and run ``hello_moveit``:
```suggestion
In a new terminal, go to the workspace, source the workspace, and run ``hello_moveit``:
```

2022-05-20 16:51 UTC, tylerjw commented
> Working on running through the tutorial right now but I have a few nitpicky grammatical suggestions from my read through.

I've accepted your changes, would you mind re-reviewing this?

2022-05-20 17:58 UTC, abake48 reviewed
Couple more changes and I'll feel comfortable approving this PR

2022-05-20 17:58 UTC, abake48 commented on doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst
> +Then in your ``CMakeLists.xml`` add this line to the section of ``find_package`` statements:
```suggestion
Then in your ``CMakeLists.txt`` add this line to the section of ``find_package`` statements:
```

2022-05-20 17:58 UTC, abake48 commented on doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst
> +You'll see after you clicked the next button your application planned, added a title above the robot, and drew a line representing the tool path.
```suggestion
You'll see after you clicked the next button, your application planned, added a title above the robot, and drew a line representing the tool path.
```

2022-05-20 18:07 UTC, abake48 approved these changes
lgtm!

2022-05-20 18:09 UTC, merged