Move Group C++ Interface [WIP]
ros-planning/moveit2_tutorials pull request #62
Opened 2021-03-10 21:51 UTC by MarqRazz

This is the initial port of the Move Group C++ Interface tutorial. This tutorial is very similar to [moveit2_demo_nodes/run_move_group](https://github.com/ros-planning/moveit2/tree/main/moveit_demo_nodes/run_move_group) which is where I grabbed the launch files.

To test this code run the following:
`ros2 launch moveit2_tutorials move_group.launch.py`
`ros2 launch moveit2_tutorials move_group_interface.launch.py`

Items that I still need to address:
- [ ] Clean up code and get the markers working with rviz_visual_tools until moveit_visual_tools is ported
- [ ] Generate the webpage and see how it looks
- [ ] Add more documentation
- [ ] Get the collision scene examples working better (they tend to fail to plan)
- [ ] Add to the readme and webpage that you need `xterm` installed

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)

2021-04-05 14:36 UTC, JafarAbdi commented on doc/move_group_interface/CMakeLists.txt
> +)
We should use the YAML files from moveit_resources

```suggestion
```

2021-04-05 14:38 UTC, JafarAbdi requested changes

2021-04-05 14:38 UTC, JafarAbdi commented on doc/move_group_interface/launch/move_group.launch.py
> +    fake_joint_driver_node = Node(package='fake_joint_driver',
We replaced this node with the one from ros2_control [see](https://github.com/ros-planning/moveit2/blob/main/moveit_demo_nodes/run_move_group/launch/run_move_group.launch.py#L144)

2021-04-21 15:51 UTC, MarqRazz commented
Changes were added in #69

2021-04-21 15:51 UTC, closed without merging