Moveit_cpp Tutorial [WIP]
ros-planning/moveit2_tutorials pull request #64
Opened 2021-03-18 12:42 UTC by MarqRazz

Port of moveit_cpp tutorial to ROS2. This addresses issue #20

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Convert launch files to ROS2
- [ ] Cleanup demo and add documentation

2021-04-05 13:26 UTC, JafarAbdi requested changes
This will not work with the main branch of moveit2

2021-04-05 13:26 UTC, JafarAbdi commented on doc/moveit_cpp/config/panda_controllers.yaml
> +panda_arm_controller:
This's for the old ros2_control, we're depending on the master branch now, see [run_moveit_cpp.launch.py](https://github.com/ros-planning/moveit2/blob/main/moveit_demo_nodes/run_moveit_cpp/launch/run_moveit_cpp.launch.py)

2021-04-05 13:26 UTC, JafarAbdi commented on doc/moveit_cpp/config/controllers.yaml
> +controller_names:
We should use the one from [moveit_resources](https://github.com/ros-planning/moveit_resources/blob/ros2/panda_moveit_config/config/panda_controllers.yaml)

2021-04-05 13:26 UTC, JafarAbdi commented on doc/moveit_cpp/config/start_positions.yaml
> +fake_joint_driver_node:
This's no longer needed

2021-04-05 13:26 UTC, JafarAbdi commented on doc/moveit_cpp/config/moveit_cpp.yaml
> +moveit_cpp_tutorial:
Should we move this file to moveit_resources .?

2021-04-05 13:26 UTC, JafarAbdi commented on doc/moveit_cpp/launch/moveit_cpp_tutorial.launch.py
> +    fake_joint_driver_node = Node(package='fake_joint_driver',
We no longer depend on `fake_joint_driver` [see](https://github.com/ros-planning/moveit2/blob/main/moveit_demo_nodes/run_moveit_cpp/launch/run_moveit_cpp.launch.py#L135)

2021-04-05 13:26 UTC, JafarAbdi commented
Should we remove `run_moveit_cpp` from the MoveIt2 repo and point users to this page .?

2021-04-21 15:51 UTC, MarqRazz commented
Changed were added in #69

2021-04-21 15:51 UTC, closed without merging