Use interpolation planner instead of sampling planner for hand
ros-planning/moveit2_tutorials pull request #648
Opened 2023-03-31 12:50 UTC by sjahr

### Description

Small fix because I had issues with using the sampling-based planner for group hand when I changed it to PILZ or CHOMP.

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-planning/moveit2/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

2023-03-31 12:50 UTC, sjahr commented on doc/tutorials/pick_and_place_with_moveit_task_constructor/src/mtc_node.cpp
> +
```suggestion
```

2023-03-31 13:00 UTC, sea-bass approved these changes
Yes! I

2023-03-31 13:02 UTC, sea-bass requested changes
Could you ensure the corresponding doc is also updated to reflect this?

2023-04-04 11:24 UTC, sjahr commented on doc/tutorials/pick_and_place_with_moveit_task_constructor/src/mtc_node.cpp
> +
```suggestion

```

2023-04-04 11:26 UTC, sea-bass approved these changes

2023-04-04 11:29 UTC, henningkayser approved these changes

2023-04-04 14:03 UTC, merged