Replaced deprecated functions to reduce warnings during build
ros-planning/moveit2_tutorials pull request #726
Opened 2023-07-31 13:50 UTC by Shobuj-Paul

### Description

Replaced the following deprecated functions to reduce warnings during build.
- Replaced `setMaxVelocityScaling()` with `setMaxVelocityScalingFactor()`.
- Replaced `setMaxAccelerationScaling()` with `setMaxAccelerationScalingFactor()`.

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-planning/moveit2/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

2023-07-31 14:23 UTC, sea-bass requested changes
Looks good!

Can you also modify the corresponding `.rst` files in `doc/tutorials/pick_and_place_with_moveit_task_constructor/pick_and_place_with_moveit_task_constructor.rst`?

2023-07-31 14:58 UTC, Shobuj-Paul commented
> I think GitHub is being weird. I saw the email notification for the follow-up commit but it doesn't show up on here. Will check later.

Yep, commit showed up on the branch but not here. Maybe just some delay.

2023-08-01 12:46 UTC, Shobuj-Paul commented
Hi @sea-bass 
Check now please, the docs have also been updated.

2023-08-14 12:41 UTC, sjahr approved these changes

2023-08-18 09:22 UTC, merged